#!/bin/bash
#
#
#  'Installation script' :  Should run
# as root! (Eventually it will become a pacman
# package)
#

cp -rf pkg/* /
chmod +x /usr/share/wearablepie/scripts/button.py
chmod +x /usr/share/wearablepie/scripts/gpsservice.py
chmod +x /usr/share/wearablepie/scripts/gpsd